# Generated by Django 5.0.3 on 2024-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mataturoute',
            old_name='first_name',
            new_name='route_name',
        ),
        migrations.RemoveField(
            model_name='mataturoute',
            name='last_name',
        ),
    ]
